# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: nodejs-10-runtime
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
#            image: docker.io/openwhisk/action-nodejs-v10
            image: docker.io/openwhisk/nodejsactionbase
            env:
              - name: TARGET
                value: "Node.js Sample v1"
