---
# This role installs invokers.
- name: create invoker deployment
  shell: "kubectl apply -f {{kube_pod_dir}}/invoker.yml"

# The invoker image has a long pull timout since it needs to pull
# all of the Docker images whisk depends on.
- name: wait until Invoker is up and running
  uri:
    url: "http://invoker-{{ item }}.invoker.openwhisk:{{ invoker_port }}/ping"
  register: result
  until: result.status == 200
  retries: 50
  delay: 20
  with_sequence: start=0 count={{ invoker_count }}
