---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: openwhisk
  labels:
    name: consul
spec:
  selector:
    name: consul
  ports:
  - name: server
    protocol: TCP
    port: 8300
    targetPort: 8300
  - name: serflan-tcp
    protocol: TCP
    port: 8301
    targetPort: 8301
  - name: serflan-udp
    protocol: UDP
    port: 8301
    targetPort: 8301
  - name: serfwan-tcp
    protocol: TCP
    port: 8302
    targetPort: 8302
  - name: serfwan-udp
    protocol: UDP
    port: 8302
    targetPort: 8302
  - name: rpc
    protocol: TCP
    port: 8400
    targetPort: 8400
  - name: http
    protocol: TCP
    port: 8500
    targetPort: 8500
  - name: consuldns-tcp
    protocol: TCP
    port: 8600
    targetPort: 8600
  - name: consuldns-udp
    protocol: UDP
    port: 8600
    targetPort: 8600
