---
apiVersion: v1
kind: Service
metadata:
  name: invoker
  namespace: openwhisk
  labels:
    name: invoker
spec:
  selector:
    name: invoker
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      name: invoker
