---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: openwhisk
  labels:
    name: kafka
spec:
  selector:
    name: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
