---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
  namespace: openwhisk
  labels:
    name: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka
    spec:
      restartPolicy: Always

      containers:
      - name: kafka
        image: ches/kafka:0.10.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: "KAFKA_ADVERTISED_HOST_NAME"
          value: kafka.openwhisk
        - name: "KAFKA_PORT"
          value: "9092"
        ports:
        - name: kafka
          containerPort: 9092
