---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: openwhisk
  labels:
    name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      restartPolicy: Always
      volumes:
      - name: nginx-certs
        configMap:
          name: nginx
          items:
          - key: "openwhisk-cert.pem"
            path: openwhisk-cert.pem
          - key: "openwhisk-key.pem"
            path: openwhisk-key.pem
      - name: nginx-conf
        configMap:
          name: nginx
          items:
          - key: "nginx.conf"
            path: nginx.conf
      - name: logs
        emptyDir: {}
      containers:
      - name: nginx
        imagePullPolicy: Always
        image: danlavine/whisk_nginx
        ports:
        - name: http
          containerPort: 80
        - name: http-api
          containerPort: 443
        - name: https-admin
          containerPort: 8443
        volumeMounts:
        - name: nginx-conf
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
        - name: nginx-certs
          mountPath: "/etc/nginx/certs"
        - name: logs
          mountPath: "/logs"
