---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: openwhisk
  labels:
    name: nginx
spec:
  type: NodePort
  selector:
    name: nginx
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https-api
    - port: 8443
      targetPort: 8443
      name: https-admin
