---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: openwhisk
  labels:
    name: zookeeper
spec:
  selector:
    name: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      name: zookeeper
