---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: openwhisk
  labels:
    name: zookeeper
spec:
  selector:
    name: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      name: zookeeper
    - port: 2888
      targetPort: 2888
      name: server
    - port: 3888
      targetPort: 3888
      name: leader-election
