---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: openwhisk
  labels:
    name: couchdb
spec:
  selector:
    name: couchdb
  ports:
    - port: 5984
      targetPort: 5984
      name: couchdb
